# Generated by Django 4.1.2 on 2022-10-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_created_at_remove_article_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
    ]
