# Generated by Django 4.1.2 on 2022-10-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('GR', 'General'), ('SP', 'Sports'), ('GM', 'Gaming'), ('FD', 'Food')], default='GR', max_length=2),
        ),
    ]
