# Generated by Django 4.1.2 on 2022-10-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published'), ('SM', 'Submitted'), ('RJ', 'Rejected'), ('AR', 'Archived')], default='DR', max_length=2),
        ),
    ]
