# Generated by Django 4.1.2 on 2022-10-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
